### ISSUE TITLE
GeoStyler should support spritesheets

### ISSUE THREAD

**Issue by simonseyock** [geostyler/geostyler-mapbox-parser#290]
# Feature Request

mapbox is based on sprite sheets. The `sprite` property is referreing to an url that points to a `.png` and `.json` file, by standard the mentioned mapbox sprite api is not used.

https://docs.mapbox.com/style-spec/reference/root/#sprite

Either mapbox parser can create a base64 image or the other parsers needs to accept spritesheets and handle them.

First option: geostyler-mapbox-parser could get a feature flag if it should request and transform the spritesheets.

Second option: add sprite data information to geostyler style (spriteimage, position, size). OpenLayers supports sprites: properties offset, size in https://openlayers.org/en/latest/apidoc/module-ol_style_Icon-Icon.html

**Comment by KaiVolland** [comment]
Some things we need to do when realizing sprite support:

- extend IconLibrary with sprite support
- adapt parsers (add to unsupportedProperties)
- think about a solution to split a sprite into single images or a single image (existing library?)
