### ISSUE TITLE
Outline does not get layout property under conversion from fill symbolizer

### ISSUE THREAD

**Issue by chrrik** [geostyler/geostyler-mapbox-parser#336]
# Bug

I am using mapboxparser to transform geostyler style into mapbox style. This is my code.

```
new MapboxParser()
                .writeStyle(changedStyle)
                .then(({output}) => {
                    console.log(changedStyle, output);
                })
```
                
I am trying to hide certain layers based on some filters by setting the visibility: false in geostyler style. It mostly works, but polygons leave the outline visible. I have narrowed it down to the mapboxparser not setting visibility: 'none' on the linelayer for the outline as seen in the console print below. The polygon layer has visibility 'none', but line layer does not even have a layout prop.

![image](https://github.com/user-attachments/assets/7c187298-dfa7-491a-8412-116177a81563)

Is this something that can be fixed?

**Comment by KaiVolland** [comment]
Hey @chrrik, thanks for the report. As you already debugged that far, are you willing and able to make pull request to fix this bug. 

Otherwise this might take some time to be fixed.

**Comment by chrrik** [comment]
I believe I have fixed it, but I don't have permission to push to a new branch.

remote: Permission to geostyler/geostyler-mapbox-parser.git denied to chrrik.
fatal: unable to access 'https://github.com/geostyler/geostyler-mapbox-parser.git/': The requested URL returned error: 403

**Comment by chrrik** [comment]
The fix was to add this line on line 1312 in MapboxStyleParser.ts
`visibility: symbolizerClone?.visibility,`

**Comment by jansule** [comment]
> I believe I have fixed it, but I don't have permission to push to a new branch.

You have to create your own fork first, push to a branch in that fork, and then open a Pull Request on this repostory based on the branch in your fork.

**Comment by chrrik** [comment]
https://github.com/geostyler/geostyler-mapbox-parser/pull/337

**Comment by KaiVolland** [comment]
Hey @chrrik i released a new version with your fix. https://github.com/geostyler/geostyler-mapbox-parser/releases/tag/v6.0.1

Can you try it an close this issue if fixed?

**Comment by chrrik** [comment]
It worked! :) Thank you for all the help!
