### ISSUE TITLE
There may be some problems in converting sld to mbStyle

### ISSUE THREAD

**Issue by Chanceshine** [geostyler/geostyler-mapbox-parser#44]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `geostyler-mapbox-parser@0.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/geostyler-mapbox-parser/build/dist/MapboxStyleParser.js b/node_modules/geostyler-mapbox-parser/build/dist/MapboxStyleParser.js
index 6cc17f1..8977a0b 100644
--- a/node_modules/geostyler-mapbox-parser/build/dist/MapboxStyleParser.js
+++ b/node_modules/geostyler-mapbox-parser/build/dist/MapboxStyleParser.js
@@ -821,7 +821,7 @@ var MapboxStyleParser = /** @class */ (function () {
                 layout = this.getLayoutFromTextSymbolizer(symbolizerClone);
                 break;
             case 'Mark':
-                if (symbolizer.wellKnownName === 'Circle') {
+                if (symbolizer.wellKnownName.toLowerCase() === 'circle') {
                     layerType = 'circle';
                     paint = this.getPaintFromCircleSymbolizer(symbolizerClone);
                     layout = this.getLayoutFromCircleSymbolizer(symbolizerClone);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by jansule** [comment]
Thanks for the info @Chanceshine! We changed the values of wellKnownNames to lowercase in [geostyler-style v4](https://github.com/geostyler/geostyler-style/releases/tag/v4.0.0).

It would be awesome, if you could provide a PR for this. There are a few more occurrences where `Circle` starts in uppercase.
